version: "3.8"

services:
  mongodb_server:
    image: "mongo:4.4.2"
    container_name: "mongodb_server"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=root"
    volumes:
      - "mongodbvol:/data/db"
    ports:
      - "27017:27017"
    networks:
      - "mongonet"
  
  mongoexpress:
    image: "mongo-express:0.54"
    container_name: "mongoexpress"
    environment:
      - "ME_CONFIG_MONGODB_SERVER=mongodb_server"
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=root"
    ports:
      - "8020:8081"
    networks:
      - "mongonet"
    depends_on:
      - "mongodb_server"

volumes:
  mongodbvol:
    driver: "local"

networks:
  mongonet:
    driver: "bridge"