version: "3.8"

services:
  redis:
    image: "redis:6.0.9"
    container_name: "redis"
    volumes:
      - "redisvol:/data"
    ports:
      - "6379:6379"
    networks:
      - "redisnet"
    command: "redis-server --appendonly yes"
  
  redisinsight:
    image: "redislabs/redisinsight:1.8.2"
    container_name: "redisinsight"
    volumes:
      - "redisinsightvol:/db"
    ports:
      - "8001:8001"
    networks:
      - "redisnet"
    depends_on:
      - "redis"

volumes:
  redisvol:
    driver: "local"
  redisinsightvol:
    driver: "local"

networks:
  redisnet:
    driver: "bridge"