version: "3.8"

services:
  mysql_server:
    image: "mysql:8.0.22"
    container_name: "mysql_server"
    environment:
      - "MYSQL_ROOT_PASSWORD=mysql"
    volumes:
      - "mysqlvol:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - "mysqlnet"
  
  adminer:
    image: "adminer:4.7.8"
    container_name: "mysql_adminer"
    ports:
      - "8010:8080"
    depends_on:
      - "mysql_server"
    networks:
      - "mysqlnet"

volumes:
  mysqlvol:
    driver: "local"

networks:
  mysqlnet:
    driver: "bridge"