version: "3.8"

services:
  kafka_broker:
    image: apache/kafka-native:3.9.0
    container_name: kafka_native
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_NODE_ID=1"
      - "KAFKA_PROCESS_ROLES=broker,controller"
      - "KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093"
      - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_native:9092"
      - "KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      - "KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093"
      - "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1"
      - "KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1"
      - "KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1"
      - "KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0"
      - "KAFKA_NUM_PARTITIONS=1"
    volumes:
      - "kafkanativevol:/var/lib/kafka/data"
    networks:
      - "kafkanativenet"

  kafka_ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka_ui
    ports:
      - "9090:8080"
    environment:
      - "DYNAMIC_CONFIG_ENABLED=true"
      - "KAFKA_CLUSTERS_0_NAME=KafkaCluster_01"
      - "KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka_native:9092"
    volumes:
      - "kafkauiconfigvol:/etc/kafkaui"
    networks:
      - "kafkanativenet"
    depends_on:
      - "kafka_broker"

volumes:
  kafkanativevol:
    driver: "local"
  kafkauiconfigvol:
    driver: "local"

networks:
  kafkanativenet:
    driver: "bridge"