version: "3.8"

services:
  zookeeper:
    image: "zookeeper:3.7.0"
    container_name: "zookeeper"
    ports:
      - "2181:2181"
    networks:
      - "kafkanet"
  
  kafka_broker:
    image: "confluentinc/cp-kafka:6.2.1"
    container_name: "kafka"
    environment:
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      - "KAFKA_BROKER_ID=1"
      - "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1"
    ports:
      - "9092:9092"
    networks:
      - "kafkanet"
    depends_on:
      - "zookeeper"
  
  kafdrop:
    image: "obsidiandynamics/kafdrop:3.27.0"
    container_name: "kafdrop"
    environment:
      - "KAFKA_BROKERCONNECT=kafka:29092"
    ports:
      - "9090:9000"
    networks:
      - "kafkanet"
    depends_on:
      - "kafka_broker"

networks:
  kafkanet:
    driver: "bridge"