version: "3.8"

services: 
  elasticsearch:
    image: "elasticsearch:7.9.3"
    container_name: "elasticsearch"
    environment:
      - "node.name=elasticsearch"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - "esvol:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - "elasticnet"

  kibana:
    image: "kibana:7.9.3"
    container_name: "kibana"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - "elasticnet"
    depends_on: 
      - "elasticsearch"

volumes:
  esvol:
    driver: local

networks:
  elasticnet:
    driver: bridge